(define (problem problem-agentA2)
	(:domain agentA2)
	(:init 
		(assigned_task_list_empty)
		( = (points) 0.000000 )
		( = (costs) 0)
	)
	(:goal (and ( >= (points) 1.000000)))
	(:metric minimize (costs))
)
